### ISSUE TITLE
Site throws a error if a user creates a new rootnode and tries to open it

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Uno.Issues#1]
If you create a new root node the site throws a error.

I presume this is because the settings node is missing. There are two ways around this.
1. Disable the creation of root nodes
2. On creation of a root node the dependency's should be created.

I think the first one is the best option otherwise you will open the possibilities to create a multi-site

**Comment by nul800sebastiaan** [comment]
Thanks @FransdeJong - we'll have to have a look! 👍

**Comment by nul800sebastiaan** [comment]
This is fixed for the upcoming 8.7 release.
