### ISSUE TITLE
SVG logo breaks mobile breakpoint view

### ISSUE THREAD

**Issue by anthonydotnet** [umbraco/Umbraco.Uno.Issues#10]
I uploaded an SVG for the logo. But when you collapse the browser to a mobile view, the logo takes over the entire screen, making the website unusable. I have tried 2 SVGs so far and have the same problem.

Reproduction
------------
### Bug summary

When screen is collapsed to mobile view, a new SVG logo causes the top left header logo to take over the entire screen, which makes the website unusable.

### Specifics

I have checked multiple browsers. Chrome, Safari, Chrome on android, Edge.

### Steps to reproduce

1. In the theme node, upload a new SVG to "Logo On Dark"
2. Publish
3. Visit any webpage, then collapse the browser to the mobile breakpoint

### Expected result
Logo should disappear

### Actual result
You will hopefully see that the SVG takes over the entire screen.

**Comment by nul800sebastiaan** [comment]
Do you have the SVG file so it can be reproduced please?

**Comment by anthonydotnet** [comment]
I managed to resolve the problem.

The SVG needs to be the same size as the demo one. The css/media query seems to be breaking when the SVG is larger.

**Comment by nul800sebastiaan** [comment]
Eh.. the thing with scalable vector graphics is that they have no inherent "size" so I'm not sure I follow how that would work?

**Comment by anthonydotnet** [comment]
Strange... must have been a dodgy SVG. It was also happening with PNG for the logo.

**Comment by nul800sebastiaan** [comment]
For now I'll close this issue, let me know if you have an image that makes it break and then we can have a look.
