### ISSUE TITLE
Settings Section

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco.Uno.Issues#11]
I wonder if the Umbraco Settings section could be enabled to display a custom dashboard, or whether this would be better in Help or in the dashboard - that explains that Umbraco Uno's bigger sibling, has more options for configuring content types, and that access to this is 'coming soon' to Uno, but if you 'want to do more'... these are your options.

I think Uno is a great starting out experience for people who want to try Umbraco in the context of a fully functional platform site, but as they explore and evaluate the options, in the context of the backoffice it would be great if that hint existed... in case people felt it was too closed down and turned away from Umbraco.

Would this help allay fears that people might think Uno IS Umbraco, and all it can do?

It is just a thought.

**Comment by nul800sebastiaan** [comment]
Thanks @marcemarc - I've asked around we're working on making clear what you get during signup, payment etc. - outside of the backoffice. As soon as we open up Uno to customization (different tier) we'll make clear what else you get and why.

I've sent your feedback to the appropriate people for consideration!
