### ISSUE TITLE
Lost "Dates/Languages" step in tour group 7

### ISSUE THREAD

**Issue by filipbech** [umbraco/Umbraco.Uno.Issues#14]
A brief description of the issue goes here.

In the Uno tour the last group (about scheduling) has a step that is lost. 

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

I assume its a bug in the uno-tour-setup and not in the tour-framework itself.

### Steps to reproduce

Take the last step of the uno-tour. Follow it to the step where you are supposed to pick dates. 

### Expected result

The next step should show

### Actual result

I get an error message that it has lost the step. 

![Skærmbillede 2020-08-05 kl  12 51 24](https://user-images.githubusercontent.com/1720790/89404944-1125cc00-d71b-11ea-8b4c-d6e24412a686.png)
![Skærmbillede 2020-08-05 kl  12 51 47](https://user-images.githubusercontent.com/1720790/89404953-1420bc80-d71b-11ea-8f18-8ad5ae9539da.png)

**Comment by nul800sebastiaan** [comment]
This is fixed for the 8.7 release.
