### ISSUE TITLE
Page is black on a browser that blocks JS

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco.Uno.Issues#15]
A brief description of the issue goes here.

I've built a website using Umbraco at http://pragmatech.sydney and when I linked to it from a LinkedIn post, and someone clicked on it from the LinkedIn iPhone app, it opens in the LinkedIn embedded-browser (a version of Safari I believe). Unfortunately when it opened in this way, the content of the site didn't display, even though it looked fine when accessed on the mobile Safari app. This was a big problem because I was launching a technology company, and it looked as though I couldn't get my website to work. When I found out the next day, In the CMS, I changed the toggle for animations for each page, which had made the hero image scale up and fade in, and with this turned off the page loads ok now. Perhaps the LinkedIn embedded browser on their iPhone app didn't like the JavaScript. As this would be a problem for every business using this theme, it might be worth investigating whether there's a way to make the page load properly even with animations turned on.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

![image](https://user-images.githubusercontent.com/56826332/89870009-7feca480-dbb5-11ea-8a50-f4fcdee26173.png)

I've found a workaround (turning off the animate toggle on every affected page), but I'd like to turn this back on and still have the page work when viewed from a LinkedIn post. Suggest exploring whether a progressive enhancement technique could be used so that the page detects that javascript is disabled and loads without animation?

### Specifics

See above.

### Steps to reproduce

See above

### Expected result

Page loads completely.

### Actual result

All page elements

**Comment by ksuvec** [comment]
Thank you for reporting this. It has been fixed and released today 26-10-2020.
