### ISSUE TITLE
Intro animation not working properly in Sliders

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco.Uno.Issues#19]
When using a slider with an e.g. a Hero widget inside + something else, the intro animation will already play for all the widgets while the slider is in view - so if you change the slide to another one that has the animation property enabled, the animation will not play.

Reproduction
------------

![image](https://user-images.githubusercontent.com/56038614/91201195-70ff0980-e700-11ea-944f-61e062fea1ad.png)
Create a new Slider. Inside, add any two elements. On second element, enable the Animation.
When you load the page and change the slider to the second element - manually or automatically - the animation will not play.

### Video overview
The slider is the first element up top, the second element is the same Hero with the animate property - used for comparison.
As you can see the text/image on slider's second slide is static.
https://drive.google.com/file/d/1a8ko_E2YxJIJRkP7mbekkzQszDxQylyV/view?usp=sharing

**Comment by Z3nAg3ncy** [comment]
this applies to the text

**Comment by ksuvec** [comment]
Thank you for reporting this. It has been fixed and released today 26-10-2020.
