### ISSUE TITLE
Setting a custom "font stack" doesn't work

### ISSUE THREAD

**Issue by greystate** [umbraco/Umbraco.Uno.Issues#2]
The Theme Settings allows for setting a "Font stack" for the site and headings. However, because the value of the setting is inserted inside quotes, when providing an actual font stack (e.g., `Inconsolata, Roboto, sans-serif`) the resulting CSS rule will be invalid:

```css
font-family: "Inconsolata, Roboto, sans-serif";
```
(The quotes make the whole string the name of the desired font)

Reproduction
------------

To reproduce the bug:

* Go into the default settings for the included Theme and specify "Roboto, sans-serif" as the **Body Font** for the site
* Save and publish
* Observe that the body font rendered throughout the site, is now the browser's default (e.g. Times or similar) instead of Roboto.

Workaround
------------

You can use a custom font as long as you only specify *a single font name* in the textbox.

So a more correct description for the **Body Font** and **Heading Font** properties (for now) would be something like "Font name for _____" instead of "Font stack for _____"

**Comment by nul800sebastiaan** [comment]
Ha! Good point, thanks @greystate !

**Comment by nul800sebastiaan** [comment]
This is fixed for the upcoming 8.7 release.
