### ISSUE TITLE
Style change: allow to change sizes for headings in generic settings

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco.Uno.Issues#20]
It would be great if we could manually define the size of h1 h2 etc. tags in pixels - perhaps set from the Settings node, or via the style editor in preview mode.

**Comment by nul800sebastiaan** [comment]
Thanks @Jay-umbr - it would be good to be able to control the font sizes for a lot of different items indeed, I'll close this one as there's a very similar feature request here: https://github.com/umbraco/Umbraco.Uno.Issues/issues/17

So issue #17 will become where we track updates around controlling font sizes.
