### ISSUE TITLE
Make it possible to add rewrite rules.

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco.Uno.Issues#23]
## Description
In Uno you're unable to access the web.config and add rewrites rules e.g redirects from non-www to www or the other way around. It would be nice to be able to do that in some way the project portal being the most likely solution

**Comment by nul800sebastiaan** [comment]
This is on @ksuvec's list to investigate this sprint.

**Comment by RyuLindow** [comment]
Awesome! I spoke with him about it before writing this feature request, so maybe that's why 🤔

**Comment by RyuLindow** [comment]
I suppose that we can close this one, no?

https://our.umbraco.com/documentation/Umbraco-Uno/SEO/Manual-redirect-settings-in-uno/

**Comment by nul800sebastiaan** [comment]
Looks like it! Thanks!
