### ISSUE TITLE
Thumbnails in Widget Catalogue isn't consistent

### ISSUE THREAD

**Issue by sofietoft** [umbraco/Umbraco.Uno.Issues#25]
First of all, the thumbnails in the widgets catalogue looks AMAZING:
![image](https://user-images.githubusercontent.com/24529086/92886486-f5959b80-f413-11ea-8434-224b56e731e0.png)

However, when I have copied a widget, let's say the "Hero widget", and open the Clipboard in the widgets catalogue, the thumbnail is gone, and instead replaced with an icon.'
Consistency is great, so it would be good to use the same thumbnails in the clipboard as in the widgets catalogue.

![image](https://user-images.githubusercontent.com/24529086/92886751-37264680-f414-11ea-94cc-2ce404397c86.png)

**Comment by nul800sebastiaan** [comment]
Thanks for the report! After some investigation this was found to be an issue in CMS, which should be fixed through this issue: https://github.com/umbraco/Umbraco-CMS/issues/8990

I'll close this one and if anyone is curious about the progress they can follow the related issue.
