### ISSUE TITLE
Latest from feed not working in new Uno projects on 8.7.0

### ISSUE THREAD

**Issue by jonat123** [umbraco/Umbraco.Uno.Issues#28]
When creating a new Uno project in 8.7.0 and adding a latest  from the feed,  you are getting an error message on the site.

Reproduction
------------

### Bug summary
Uno projects on 8.7.0 throws an error if you are trying to use the latest from feed widget.

### Specifics
Uno projects on 8.7.0

### Steps to reproduce

1. Go to the project and make sure that you have a feed with some posts.

2. Go to a page and use the widget Latest from feed.

3. Just use the default settings and then choose the blog feed or other feed that you have.

4. Visit the frontend of the site and see if the feed with blogs shows.

### Expected result
Excpeted to see the feed to be shown on the frontpage and frontend of the site

### Actual result
It throws an error:  CS0019: Operator '>' cannot be applied to operands of type 'string' and 'int'
![image](https://user-images.githubusercontent.com/54025331/93454651-8c160100-f8db-11ea-924c-a132bd862624.png)

**Comment by nul800sebastiaan** [comment]
This one is now fixed and will be released soon!
