### ISSUE TITLE
Preview mode still shows if you have it running in a separate tab

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco.Uno.Issues#3]
Reproduction
------------
### Bug summary

A brief description of the issue goes here.

You want to take advantage of the preview functionality and the quick editor (paint brush). 

Edit a content node so that it fits your style, which you then saves when happy with the result. 
Then the content editor opens a new tab to see the result.

But the preview mode is still enable, because it hasn't been shut off in the other tab.

### Specifics

Umbraco 8.6.2
Forms 8.4.1
Deploy 3.4.5

Bug will occur if you have the url with the preview running in a tab or forget to shut it down before opening the some content node again.

In preview mode
![image](https://user-images.githubusercontent.com/32164310/84489363-e6cb0b80-aca1-11ea-8381-5ebfdef40006.png)

regular:
![image](https://user-images.githubusercontent.com/32164310/84489468-0f530580-aca2-11ea-85f7-d0eb73acbba1.png)

Checked in Firefox, Brave, Google Chrome

### Steps to reproduce

Find a content node. 
Click preview.
Edit the header.
Click save.
Open a new tab and navigate to the same content node, without the preview affix.
### Expected result

I expected to see the page and the changes made to it.

### Actual result

I got the actual page and the changes made to it, but the preview mode was still enable.

**Comment by nul800sebastiaan** [comment]
Hi Eric, I think you're just a bit confused as to how this is supposed to work, you describe making changes without publishing them and then expecting to see the page with the changes made to it, which is exactly what you got. Yes preview mode is still enabled, that's exactly what you wanted in your expected result: to see a preview.

Preview mode ends by exiting preview mode manually or by closing the browsers and starting fresh (it's based on a cookie that is valid for the current session, which means: until you close the browser).

This is how preview mode in Umbraco works in general and there's no plans to change that at the moment.
