### ISSUE TITLE
Mobile height under Settings > Template is missing px after the value

### ISSUE THREAD

**Issue by MahmoudUmbraco** [umbraco/Umbraco.Uno.Issues#32]
Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

**Comment by nul800sebastiaan** [comment]
Can you be more specific please? I don't know where to look, this looks fine to me? 

![image](https://user-images.githubusercontent.com/304656/94425649-90200980-018c-11eb-9470-b0217462835f.png)

**Comment by MahmoudUmbraco** [comment]
Sorry, I added some images but it didnt show in up in the description.

I have investigated more and I have found out when and how to reproduce.

How to reproduce:

Go to preview.
open the toggle view explorer.
Under header, change the value of mobile height. In my example I changed it from 50 to 60.
Go back to the backoffice. 
Open settings/theme and you will see that mobile height doesn't have px.

**Comment by hartviglarsen** [comment]
Some images for ya:

If you set the mobile height in the preview thingy:

![image](https://user-images.githubusercontent.com/4366314/94430104-a8dfed80-0193-11eb-9088-c547690b9410.png)

The actual setting (once saved) won't include `px`:
![image](https://user-images.githubusercontent.com/4366314/94430141-b7c6a000-0193-11eb-96dc-4aa099409cd7.png)

**Comment by nul800sebastiaan** [comment]
Makes sense now, thanks guys! 👍 We'll have to have a look it in the next sprint.

**Comment by ksuvec** [comment]
Thank you for reporting this. It has been fixed and released today 26-10-2020.
