### ISSUE TITLE
Logo squeezes together on larger menus

### ISSUE THREAD

**Issue by hjaltedaniel-umbraco** [umbraco/Umbraco.Uno.Issues#35]
If you have a large menu, the logo squeezes together - especially on smaller screens.
This does not seem to be the intended behaviour. I would expect 

Reproduction
------------

Make a few additional content items as a child of the root node, and it will start to show.

### Bug summary

![image](https://user-images.githubusercontent.com/61144403/94899100-fb225680-0492-11eb-9b33-62f43880a9f1.png)

### Expected result
I see several possible alternatives. One possibility could be for a hamburger menu to show up if the menu is large. Another possibility could be to split the menu in another line. Lastly the last menu items could just be cropped.

### Actual result
Squeezed and ugly logo

**Comment by ksuvec** [comment]
Thank you for reporting this. It has been fixed and released today 26-10-2020.
