### ISSUE TITLE
Mobile header height does not have "px" added when saved in Preview mode

### ISSUE THREAD

**Issue by hjaltedaniel-umbraco** [umbraco/Umbraco.Uno.Issues#36]
If you save a change to your template using the preview mode, the Mobile header height does not have px added. This causes the header to fill up the entire screen after saving with preview mode.

Reproduction
------------

### Bug summary

When using the preview mode to save a change made to the template, the value in the "Height Mobile" field does not have a px value added to it.
![image](https://user-images.githubusercontent.com/61144403/94899638-f27e5000-0493-11eb-8ffa-9c4994d6964d.png)

### Steps to reproduce

Make a change on a empty uno project, using preview mode, when this change is saved the "Height Mobile" value should show up without the additional px added.

### Expected result

That field should have the same behaviour as the other fields - so it should have "px" added to the value inputted in preview mode.

### Actual result
The value stays as it is, causing the mobile header to fill the entire screen.
![image](https://user-images.githubusercontent.com/61144403/94899845-4ee16f80-0494-11eb-8891-18e5b3815956.png)

**Comment by nul800sebastiaan** [comment]
Duplicates #32
