### ISSUE TITLE
Datepicker in Uno Umbraco Forms does not render

### ISSUE THREAD

**Issue by anthonydotnet** [umbraco/Umbraco.Uno.Issues#38]
### Bug summary
Datepicker in Uno Umbraco Forms does not render. I only see a textbox.

### Specifics
    Where applicable:
    * All URLS
    * Latest Uno
    * Chrome
* No errors in console

### Steps to reproduce
1. Create a form with a datepicker, and add it to a page.
2. Visit the public page.
You will see there is no date picker.. only a textbox.

### Expected result
Datepicker should be rendered.

### Actual result
Only textbox rendered.

**Comment by anthonydotnet** [comment]
Something else to note is that even though I can add a value manually, that value is not posted in the form.

**Comment by nul800sebastiaan** [comment]
Looks like we're not including the `pikaday` dependency in the frontend at the moment, we'll have to have a look at that one!

**Comment by ksuvec** [comment]
Thank you for reporting this. It has been fixed and released today 26-10-2020.
