### ISSUE TITLE
Carousel has moving buttons /about-us/

### ISSUE THREAD

**Issue by anthonydotnet** [umbraco/Umbraco.Uno.Issues#4]
On the /about-us/ page, there is a carousel at the bottom of the page.

When clicking on the next & previous buttons, these buttons move up and down depending on the height of the content. They should stay in the same position.

Reproduction
------------
Go to /about-us/
Scroll down to the carousel
Click the ">" icon - Notice that it moves vertically each time it is clicked

**Comment by nul800sebastiaan** [comment]
Thanks @anthonydotnet - we'll have to have a look!

**Comment by ksuvec** [comment]
Thank you for reporting this. It has been fixed and released today 26-10-2020.
