### ISSUE TITLE
Big Navigation is not highlighted when a subpage is active

### ISSUE THREAD

**Issue by stephenalion** [umbraco/Umbraco.Uno.Issues#40]
I've made a custom navigation in Umbraco Uno. I've used Big Navigation and Navigation Item. When I click on a link which is a Navigation Item, it's highlighted in orange. But when I click on a subpage from Big Navigation, the Big Navigation link is not highlighted.

### Specifics
It's on https://helin.s1.umbraco.io/services/quickscan/, the latest version of Umbraco and it's in Firefox as well as in Chrome.
![Schermafbeelding 2020-10-06 om 16 23 19](https://user-images.githubusercontent.com/72454974/95214663-a60e7980-07df-11eb-8df2-328d3fe33f16.png)
![Uploading Schermafbeelding 2020-10-06 om 16.23.14.png…]()

### Expected result
I expect that the Big Navigation link is also highlighted when clicking on a subpage.

**Comment by nul800sebastiaan** [comment]
Thanks, that seems to be a bug we need to look into! It's strange that this works on a new Uno site I just created. I'll have to ask the team if this was fixed recently.

**Comment by ksuvec** [comment]
Thank you for reporting this. It has been fixed and released today 26-10-2020.
