### ISSUE TITLE
The search bar doesn't work

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco.Uno.Issues#42]
A brief description of the issue goes here.

The search bar does not work. At all.

Reproduction
------------

Try to enter anything into the search bar. You will get 0 results

### Bug summary

![image](https://user-images.githubusercontent.com/56826332/95982176-180a4280-0e20-11eb-8905-62afce5f03b6.png)

I have a node called "Spa", so I searched for that, yet there are no results.

### Specifics

Umbraco 8.7

### Steps to reproduce

1. Open the search bar.
2. Enter the name of any node you have on your site.

### Expected result

I get the spa node in results.

### Actual result

no results

**Comment by ksuvec** [comment]
Thank you for reporting this. It has been fixed and released today 26-10-2020.

**Comment by RyuLindow** [comment]
Nice 😊
