### ISSUE TITLE
Header should not display a search Link and a Search Icon.

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco.Uno.Issues#5]
Reproduction
------------
### Bug summary

If you enable the search node to be visible from the front-end it will display both the search link and the search Icon.

There shouldn't be a need for both as they have the same functionality.

### Specifics

Will only appear if it is enable in the backoffice. Look in Steps to reproduce to enable it.

Looks like this when you enable the search
![image](https://user-images.githubusercontent.com/32164310/84502517-c3f82180-acb8-11ea-80ac-fe23ee900d97.png)

Uno version:
Umbraco 8.6.2
Forms 8.4.1
Deploy 3.4.5

### Steps to reproduce

Navigate to the Search node 
![image](https://user-images.githubusercontent.com/32164310/84502611-fc97fb00-acb8-11ea-8ba5-bfb9afcecde7.png)

Click on it and scroll down to the bottom and uncheck this setting:
![image](https://user-images.githubusercontent.com/32164310/84502725-2bae6c80-acb9-11ea-8db3-2ca18912742d.png)

### Expected result

That I either got a search link or a search icon. Or that I could choose between what I wanted.

### Actual result

I got both.

**Comment by nul800sebastiaan** [comment]
This is fixed for the upcoming 8.7 release.
