### ISSUE TITLE
Make RTE more flexible by allowing changes in the "view source code" option

### ISSUE THREAD

**Issue by jesperlange** [umbraco/Umbraco.Uno.Issues#56]
When you edit in "View source code" in RTE, you can to some extend do inline styling - which is not optimal but better than nothing.

However, if you want to add something, like icons through Font Awesome, it will have to be done separately in a "Code" Widget 

An example of what can be done, and what disappears:
![image](https://user-images.githubusercontent.com/54025229/99036702-73943100-2582-11eb-9843-4d916094dded.png)

The color green stays, while the icon doesn't get included

![image](https://user-images.githubusercontent.com/54025229/99036751-860e6a80-2582-11eb-8cd7-b9474a5fb1f9.png)

**Comment by limpa123** [comment]
Hi @jesperlange, I believe that <i> is not an allowed element in the RTE. But if you instead use a **span**, it will work.
 `<span class="fa fa-phone" aria-hidden="true"></span>`

**Comment by nul800sebastiaan** [comment]
👍 We'll close this one, indeed the html should be valid so that would be the advise, thanks for the input @limpa123 !
