### ISSUE TITLE
Copying a Widget only copies Content and not Settings.

### ISSUE THREAD

**Issue by HamDerAndrew** [umbraco/Umbraco.Uno.Issues#58]
When copying content in a Widget, the settings of the original content is not applied.

Reproduction
------------
### Bug summary

When you want to copy Content from a Widget you only copy the Widget's Content and not its Settings.

### Specifics

    * What version are you using
Umbraco.Core.dll: 8.9.1
Umbraco.Forms.Core.dll: 8.5.5
Umbraco.Courier.Core.dll:
Umbraco.Deploy.dll: 3.5.2
Umbraco.Deploy.Contrib.Connectors.dll: 3.0.2
ClientDependency.Core.dll: 1.9.9
Umbraco.Cloud.Headless.dll:
Umbraco.Cloud.StorageProviders.AzureBlob.dll: 3.0.1

    * What browser and version you are using
Chrome version 87.0.4280.88

### Steps to reproduce

**Step 1:** 
Copy the Widget Content

![step 1 copy widget ](https://user-images.githubusercontent.com/2794633/101768799-5ea9af80-3ae6-11eb-9eb1-fdef46ac1ecc.png)

**Step 2:** 
Select where you want to add the content with the Widget

![step 2 select content to insert](https://user-images.githubusercontent.com/2794633/101768997-9ca6d380-3ae6-11eb-95b5-81245251719a.png)

**Step 3:**
Check how the copied content looks compared to the original (in this case you already see the settings are not applied):

![step 3 inserted content](https://user-images.githubusercontent.com/2794633/101769180-ded01500-3ae6-11eb-9c27-c8e0d6e7ff3b.png)

### Expected result

It is expected that the copied Content would have the same Settings as the original it was copied from.

### Actual result

The Settings of the Content is not applied to the copied content:

**Original content Settings:**

![step 4 settings](https://user-images.githubusercontent.com/2794633/101769492-5605a900-3ae7-11eb-8613-ac84192bc876.png)

**Copied content Settings:**

![step 5 copied settings are default settings](https://user-images.githubusercontent.com/2794633/101769548-6a49a600-3ae7-11eb-9d1b-62b41664d6e1.png)

**Comment by nul800sebastiaan** [comment]
Thanks, this is fixed for Umbraco 8.10 which is due out soon (hopefully this week) https://github.com/umbraco/Umbraco-CMS/issues/8990
