### ISSUE TITLE
Minify CSS

### ISSUE THREAD

**Issue by anthonydotnet** [umbraco/Umbraco.Uno.Issues#60]
CSS is currently not minified. This slows down user experience and also ranks the website lower on google pagespeed.

Example:
https://umbr.coach/css/ig-base.css?cdv=1041439384

Please minify the CSS.

**Comment by limpa123** [comment]
I believe it is through the DependencyHandler once the site is no longer in debug mode.
![image](https://user-images.githubusercontent.com/2033070/103769018-d9051b00-5023-11eb-8029-cad57fb8bc59.png)

**Comment by nul800sebastiaan** [comment]
Thanks @limpa123 - I can confirm that when Debug is off then all of this is automatically minified using ClientDepency.

**Comment by anthonydotnet** [comment]
This is not the case for me. Debug is off, and I restarted the app twice.

Still not minified.

**Comment by anthonydotnet** [comment]
Here is the non-minified css: https://umbr.coach/css/ig-base.css?cdv=1041439384

As you can see debug is off:
<img width="291" alt="Screenshot 2021-01-07 at 03 37 25" src="https://user-images.githubusercontent.com/11291788/103795125-b3b2f400-5099-11eb-9620-4937b4826004.png">

**Comment by nul800sebastiaan** [comment]
The file itself never touched, but your html output includes the minimized version:

![image](https://user-images.githubusercontent.com/304656/103795811-b9cbb500-5046-11eb-8f00-1f03536e36b2.png)

**Comment by anthonydotnet** [comment]
Ah ok. My bad. I can't believe I missed this!

Thanks for the help!
