### ISSUE TITLE
Add a Forgot Password widget

### ISSUE THREAD

**Issue by anthonydotnet** [umbraco/Umbraco.Uno.Issues#62]
Uno has a login, but it does not have a forgot password widget.

A member should be allowed to change/reset their password if they forget it.

**Comment by nul800sebastiaan** [comment]
This has the same answer as https://github.com/umbraco/Umbraco.Uno.Issues/issues/59#issuecomment-748001880 for now.

**Comment by anthonydotnet** [comment]
Ah... I couldnt find that, so I created another one. Sorry.
