### ISSUE TITLE
Uno doesn't display fonts and colors correctly in Internet Explorer

### ISSUE THREAD

**Issue by TSKPraha** [umbraco/Umbraco.Uno.Issues#64]
Hi,

I got problem with my website:

https://tsks-loyal-turtle.s1.umbraco.io
Umbraco Deploy 3.5.4
UMBRACO UNO

COLORS and FONTS on texts doesnt show up properly.
Texts colors typical for „hyperlinked texts“ probably overrides „Theme settings“ in preview editor.
So, blue or purple colors of texts appears instead of black texts. (But animation of text transparency when cursor overlaps texts still works properly)
There is also issue with diacritics - „Ě“ „Š“.

This happens only in Internet Explorer (using actual version)
Other browser like Opera, Opera GX, Chrome, ME Edge works correctly.
Please, check attachments.

Unfortunately, in our company work a lot of people using IE and Im making Thematic Micro-Site for them.

Thanks for your help!
David, TSK

![Question Other browsers](https://user-images.githubusercontent.com/79532544/108881458-9fa06300-7603-11eb-8b6a-05d958126d18.png)
![Question IE](https://user-images.githubusercontent.com/79532544/108881459-a0d19000-7603-11eb-9f80-28afe984544c.png)

A brief description of the issue goes here.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

**Comment by nul800sebastiaan** [comment]
Hi there @TSKPraha - unfortunately, Internet Explorer will be completely deprecated in August this year (https://www.theverge.com/2020/8/17/21372487/microsoft-internet-explorer-11-support-end-365-legacy-edge#:~:text=In%20exactly%20a%20year%2C%20on,support%20ending%20on%20November%2030th. ) and therefore we do not offer support for it any more.
