### ISSUE TITLE
Issue creating an Uno Project when using any other link then the landing page

### ISSUE THREAD

**Issue by ctf-umbraco** [umbraco/Umbraco.Uno.Issues#7]
When you try to create an uno project by clicking any other link then the one given on the landing page you will get an error.

Reproduction
------------

One way to reproduce this is to use the Linked in link on a phone, that should trigger the error.

It will also trigger if you use your umbraco.com credentials rather then cloud credentials.

**Comment by nul800sebastiaan** [comment]
Thanks @ctf-umbraco - after talking to people I think we'll close this for now, if you have steps to reproduce this problem exactly and what the wrong link is and where to find it exactly then we can re-open it! 👍
