### ISSUE TITLE
Tour 4: "Inviting a colleague to the project" breaks at step 7

### ISSUE THREAD

**Issue by hjaltedaniel-umbraco** [umbraco/Umbraco.Uno.Issues#81]
When running through tour 4: Inviting a colleague to the project it breaks at step 7, because the "Add" button is not clickable.

Reproduction
------------
When hitting step 7, the box that marks the current step does not move to the next field:
![image](https://user-images.githubusercontent.com/61144403/118491658-80573480-b71f-11eb-8a11-b6c4649538d3.png)

### Steps to reproduce
Run through the tour - you'll hit the error by step 7.

### Expected result
"Add" should be highlighted, you should be able to click it - and by that continue the tour.

### Actual result
"Add" is not highlighted and you have to end the tour at step 7/12

**Comment by nul800sebastiaan** [comment]
Looks like the order of the steps is wrong, it skips from "email" to "message" while the UI has the "add user group" step in between that. 

Uploading Uno81.mp4…
